### PR TITLE
SocialManager/Core: Fix for chat handler delegates

### LINKED ISSUE #222: [Bug] Social/Core: Chat Handler delegation now fails
Date: November 13th, 2019

Description: It appears that Chat Handlers are now not being Initialised properly when the SocialManager class is loaded.

Occurrence: All.

OS: Windows 10

Branch/Commit: develop

STR:

1. Boot up a server with a fresh develop branch
2. Login to the game
3. Try and write things in /say, /emote, or /yell.

Observed: The Debug text comes back saying "SocialManager: Currently not implemented" for each time you try to "say" something.
The emote commands like `/laugh` and such still work

Expected: The debug text does not come back and your message goes through.

### PR DESCRIPTION
**Pull request by kirmmin**
Fixes #222

### CODE REVIEW

File: Source/NexusForever.WorldServer/Game/Social/SocialManager.cs [hunk 1]
```diff
@@ -59,8 +59,15 @@ private void InitialiseChatHandlers()
                     Debug.Assert(typeof(ClientChat) == parameterInfo[1].ParameterType);
                     #endregion
 
-                    ChatChannelHandler @delegate = (ChatChannelHandler)Delegate.CreateDelegate(typeof(ChatChannelHandler), method);
-                    chatChannelHandlers.Add(attribute.ChatChannel, @delegate);
+                    var c1 = Expression.Parameter(typeof(WorldSession));
```
Comment (Rawaho) [inline Source/NexusForever.WorldServer/Game/Social/SocialManager.cs]: You shouldn't need to generate a delegate from an expression tree, CreateDelegate supports both static and instance methods.

Comment (kirmmin) [reply Source/NexusForever.WorldServer/Game/Social/SocialManager.cs]: I thought the same thing, but I was getting errors trying to use `CreateDelegate`. I'll take another look later.

**Review by kirmmin — COMMENTED** [review]
Converted back to Delegate. Issue was that I wasn't giving the `CreateDelegate` method the correct instance to bind the method against :)

This is the method I needed to use, for future reference: https://docs.microsoft.com/en-us/dotnet/api/system.delegate.createdelegate?view=netframework-4.8#System_Delegate_CreateDelegate_System_Type_System_Object_System_Reflection_MethodInfo_
