### PR TITLE
Bug Fix: Teleporting & Ability use while mounted

### LINKED ISSUE #117: Issues while mounted
- Spell effect animations play while mounted.
- No way of tracking user mounted state, currently.
   - Do we plan on adding player flags to the class? I know some will get recognised in game by LUA by the entity state, but it's good to track this server side, too.

Extends #113

### LINKED ISSUE #118: Additional issues while mounted
Bike mounts like the Uniblades or lever mounts like Igneous Strider have the incorrect player appearance pose. 

Teleporting while mounted: Depending on zone the player will either end up with the player appearance bug in #113 or end up teleported to XYZ coordinates of 0, 0, 0 for given target zoneID.

To reproduce:
1- Mount up
2- !go Thayd or !go Illium
3- Go skydiving for a bit

Extends #117 and #113

### PR DESCRIPTION
**Pull request by kirmmin**
Fixes #117 
Fixes #118

### CODE REVIEW

File: Source/NexusForever.WorldServer/Game/Entity/UnitEntity.cs [hunk 1]
```diff
@@ -73,6 +73,17 @@ public void CastSpell(SpellParameters parameters)
             if (parameters == null)
                 throw new ArgumentNullException();
 
+            if (GetType() == typeof(Player))
```
Comment (ahoiahoi) [inline Source/NexusForever.WorldServer/Game/Entity/UnitEntity.cs]: might want to use "if (this is Player player)" instead

File: Source/NexusForever.WorldServer/Game/Entity/Player.cs [hunk 2]
```diff
@@ -536,6 +538,42 @@ public void TeleportTo(WorldEntry entry, Vector3 vector, uint instanceId = 0u, u
...
+        }
+
+        /// <summary>
+        /// Dismounts this <see cref="Player"/> from a vehicle that it's attached to
+        /// </summary>
+        public void Dismount()
+        {
+            if (VehicleGuid != 0u)
+            {
+                Vehicle vehicle = GetVisible<Vehicle>(VehicleGuid);
```
Comment (Fabi) [inline Source/NexusForever.WorldServer/Game/Entity/Player.cs:802]: Possible null reference?

**Comment by kirmmin** [comment]
Rebased today to the latest `develop` branch.

Went through the packets today and discovered that there was an inconsistency with retail sniffs when dismounting, specifically around the fact that the EntityCommand packet update was not sent on Retail. The sniffs I have with a player being removed from a mount never had a `ServerEntityCommand` packet sent after removal.
Removing that prevented the client "responding" to the EntityCommand instruction with it's own request.

This is the line I removed: https://github.com/NexusForever/NexusForever/pull/158/files#diff-c73a1edb9532580b34666eac934fb1daL234

I tested Dismounting, Dismount from Teleport, Logging out, and ALT+F4-ing client. None of these events triggered the exception we were seeing before (or other exceptions for that matter). I tested this with 2 clients open, as well, and was able to see the appropriate updates to both clients, so I assume the Broadcast was just an oversight. This may well be finally resolved :)

Removing WIP
